# Generated by Django 6.0.5 on 2026-08-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="clicks",
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField()),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "link_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="links.link",
                    ),
                ),
            ],
        ),
    ]
