# Generated by Django 6.0.5 on 2026-08-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_remove_link_clicks_click"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
