# Generated by Django 6.0.5 on 2026-05-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
